<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45;net8.0</TargetFrameworks>
    <RootNamespace>CloudWars.SpaceBattle</RootNamespace>
    <AssemblyName>CloudWars.SpaceBattle</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CloudWars.Common\CloudWars.Common.csproj" />
    <ProjectReference Include="..\CloudWars.Entities\CloudWars.Entities.csproj" />
    <ProjectReference Include="..\CloudWars.DataAccess\CloudWars.DataAccess.csproj" />
  </ItemGroup>
</Project>
