<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net45;net8.0</TargetFrameworks>
    <RootNamespace>CloudWars.DataAccess</RootNamespace>
    <AssemblyName>CloudWars.DataAccess</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Queue\**" />
    <Compile Remove="Storage\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Needletail.DataAccess">
      <HintPath>..\packages\Needletail.DataAccess.1.0.0.3\lib\net40\Needletail.DataAccess.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.SqlServer.Types">
      <HintPath>..\packages\Needletail.DataAccess.1.0.0.3\lib\net40\Microsoft.SqlServer.Types.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CloudWars.Entities\CloudWars.Entities.csproj" />
  </ItemGroup>
</Project>
