<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7" />
    <PackageReference Include="xunit.runner.console" Version="2.7.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudWars.SpaceBattle\CloudWars.SpaceBattle.csproj" />
    <ProjectReference Include="..\CloudWars.DataAccess\CloudWars.DataAccess.csproj" />
    <ProjectReference Include="..\CloudWars.Entities\CloudWars.Entities.csproj" />
    <ProjectReference Include="..\CloudWars.Common\CloudWars.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="connections.local.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
